# ========================================
# SERVER
# ========================================

server.port=8080
spring.application.name=API-GATEWAY


# ========================================
# EUREKA
# ========================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true


# ========================================
# JWT
# ========================================

jwt.secret=MySuperSecretKeyForJWTAuthenticationInLogisticsProject123456!
jwt.expiration=86400000


# ========================================
# GATEWAY DISCOVERY
# ========================================

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# ==========================================================
# 0. PACKAGE - READ
# USER + ADMIN
# GET /api/packages
# GET /api/packages/{trackingNumber}
# ==========================================================

spring.cloud.gateway.routes[0].id=PACKAGE-SERVICE-READ
spring.cloud.gateway.routes[0].uri=lb://PACKAGE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/packages/**
spring.cloud.gateway.routes[0].predicates[1]=Method=GET
spring.cloud.gateway.routes[0].filters[0]=JwtAuthentication
spring.cloud.gateway.routes[0].filters[1].name=RoleAuthorization
spring.cloud.gateway.routes[0].filters[1].args.roles=USER,ADMIN


# ==========================================================
# 1. PACKAGE - CREATE
# ADMIN ONLY
# POST /api/packages
# ==========================================================

spring.cloud.gateway.routes[1].id=PACKAGE-SERVICE-CREATE
spring.cloud.gateway.routes[1].uri=lb://PACKAGE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/packages
spring.cloud.gateway.routes[1].predicates[1]=Method=POST
spring.cloud.gateway.routes[1].filters[0]=JwtAuthentication
spring.cloud.gateway.routes[1].filters[1].name=RoleAuthorization
spring.cloud.gateway.routes[1].filters[1].args.roles=ADMIN


# ==========================================================
# 2. PACKAGE - UPDATE STATUS
# ADMIN ONLY
# PUT /api/packages/{trackingNumber}/status
# ==========================================================

spring.cloud.gateway.routes[2].id=PACKAGE-SERVICE-UPDATE
spring.cloud.gateway.routes[2].uri=lb://PACKAGE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/packages/*/status
spring.cloud.gateway.routes[2].predicates[1]=Method=PUT
spring.cloud.gateway.routes[2].filters[0]=JwtAuthentication
spring.cloud.gateway.routes[2].filters[1].name=RoleAuthorization
spring.cloud.gateway.routes[2].filters[1].args.roles=ADMIN


# ==========================================================
# 3. TELEMETRY - READ
# USER + ADMIN
# GET /api/telemetry/{trackingNumber}/history
# GET /api/telemetry/{trackingNumber}/latest
# ==========================================================

spring.cloud.gateway.routes[3].id=TELEMETRY-SERVICE-READ
spring.cloud.gateway.routes[3].uri=lb://TELEMETRY-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/telemetry/**
spring.cloud.gateway.routes[3].predicates[1]=Method=GET
spring.cloud.gateway.routes[3].filters[0]=JwtAuthentication
spring.cloud.gateway.routes[3].filters[1].name=RoleAuthorization
spring.cloud.gateway.routes[3].filters[1].args.roles=USER,ADMIN


# ==========================================================
# 4. TELEMETRY - UPDATE
# ADMIN ONLY
# POST /api/telemetry
# ==========================================================

spring.cloud.gateway.routes[4].id=TELEMETRY-SERVICE-UPDATE
spring.cloud.gateway.routes[4].uri=lb://TELEMETRY-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/telemetry
spring.cloud.gateway.routes[4].predicates[1]=Method=POST
spring.cloud.gateway.routes[4].filters[0]=JwtAuthentication
spring.cloud.gateway.routes[4].filters[1].name=RoleAuthorization
spring.cloud.gateway.routes[4].filters[1].args.roles=ADMIN


# ==========================================================
# 5. ROUTING - READ ETA
# USER + ADMIN
# GET /api/routing/{trackingNumber}
# ==========================================================

spring.cloud.gateway.routes[5].id=ROUTING-SERVICE-READ
spring.cloud.gateway.routes[5].uri=lb://ROUTING-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/routing/**
spring.cloud.gateway.routes[5].predicates[1]=Method=GET
spring.cloud.gateway.routes[5].filters[0]=JwtAuthentication
spring.cloud.gateway.routes[5].filters[1].name=RoleAuthorization
spring.cloud.gateway.routes[5].filters[1].args.roles=USER,ADMIN


# ==========================================================
# 6. ROUTING - CALCULATE ETA
# ADMIN ONLY
# POST /api/routing/calculate
# ==========================================================

spring.cloud.gateway.routes[6].id=ROUTING-SERVICE-CALCULATE
spring.cloud.gateway.routes[6].uri=lb://ROUTING-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/routing/calculate
spring.cloud.gateway.routes[6].predicates[1]=Method=POST
spring.cloud.gateway.routes[6].filters[0]=JwtAuthentication
spring.cloud.gateway.routes[6].filters[1].name=RoleAuthorization
spring.cloud.gateway.routes[6].filters[1].args.roles=ADMIN


# ==========================================================
# 7. NOTIFICATION - READ
# USER + ADMIN
# GET /api/notifications/track/{trackingNumber}
# ==========================================================

spring.cloud.gateway.routes[7].id=NOTIFICATION-SERVICE-READ
spring.cloud.gateway.routes[7].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[7].predicates[1]=Method=GET
spring.cloud.gateway.routes[7].filters[0]=JwtAuthentication
spring.cloud.gateway.routes[7].filters[1].name=RoleAuthorization
spring.cloud.gateway.routes[7].filters[1].args.roles=USER,ADMIN


# ==========================================================
# 8. NOTIFICATION - UPDATE
# ADMIN ONLY
# POST /api/notifications/update
# ==========================================================

spring.cloud.gateway.routes[8].id=NOTIFICATION-SERVICE-UPDATE
spring.cloud.gateway.routes[8].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/notifications/update
spring.cloud.gateway.routes[8].predicates[1]=Method=POST
spring.cloud.gateway.routes[8].filters[0]=JwtAuthentication
spring.cloud.gateway.routes[8].filters[1].name=RoleAuthorization
spring.cloud.gateway.routes[8].filters[1].args.roles=ADMIN


# ========================================
# LOGGING
# ========================================

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.reactive.result.method.annotation=TRACE